name: login_app
description: Final Project by Chakravarty Srinjoy and Thakkar Hardik.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  transparent_image: 2.0.0
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.2
  firebase_ml_vision: 0.12.0
  firebase_core: 1.0.3
  firebase_database: 6.1.2
  image_picker: 0.7.4
  firebase_storage: 8.0.3
  permission_handler: 6.1.1
  firebase_auth: 1.0.3
  fluttertoast: 8.0.3
  extended_image: 4.0.1
  flutter_screenutil: 5.0.0
  cloud_firestore: 1.0.5
<<<<<<< Updated upstream
=======
  google_sign_in: 4.5.9
  camera: 
  path_provider: 2.0.1
  path: 1.8.0
  multi_image_picker: 4.8.0
  
  #Future release work resume point
  # flutter_facebook_auth: "^1.0.0"
  # sign_in_with_apple: ^2.5.2
  # crypto: ^2.1.5
  # flutter_twitter_login: ^1.1.0
  # github_sign_in: ^0.0.1
  # location: 
>>>>>>> Stashed changes

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "icon/icon.png"
  image_path_android: "icon/icon.png"
  image_path_ios: "icon/icon.png"
  adaptive_icon_background: "icon/icon.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "icon/icon.png" # only available for Android 8.0 devices and above

flutter:
  assets:
    - images/
    - assets/
  uses-material-design: true
